#!/usr/bin/env python3
"""
gen_fonts.py - turn Spleen BDF files into src/LB_Fonts.cpp.

    python3 tools/gen_fonts.py spleen-5x8.bdf spleen-8x16.bdf

Same pattern as LonelyBinaryDisplay's tools/gen_panels.py: the generated file is
never hand-edited, and re-running this after changing a source font is how it
gets updated.

Why Spleen: BSD 2-Clause, by Frederic Cambus. Every other obvious candidate for
CJK later (GNU Unifont, WenQuanYi) is GPL with a font-embedding exception, and
whether firmware counts as "a document" for that exception is a grey area we do
not need to enter. efont, which we will use for Chinese, is BSD 3-Clause for the
same reason.

Output format: ASCII 32..126 only, one byte per row per 8 pixels of width,
stored top row first. Deliberately trivial to render - the decoder in
LB_Canvas.cpp is a dozen lines, and a font nobody references costs zero flash
because the linker drops it.
"""
import sys, os, re

def parse_bdf(path):
    w = h = None
    glyphs = {}
    enc = None
    rows = None
    for line in open(path, encoding='latin-1'):
        line = line.rstrip('\n')
        if line.startswith('FONTBOUNDINGBOX'):
            p = line.split()
            w, h = int(p[1]), int(p[2])
        elif line.startswith('ENCODING'):
            enc = int(line.split()[1])
        elif line == 'BITMAP':
            rows = []
        elif line == 'ENDCHAR':
            if enc is not None and rows is not None:
                glyphs[enc] = rows
            enc, rows = None, None
        elif rows is not None:
            rows.append(line.strip())
    return w, h, glyphs

def emit(path, out):
    w, h, glyphs = parse_bdf(path)
    bytes_per_row = (w + 7) // 8
    name = f"LB_Font{w}x{h}"
    data = []
    for code in range(32, 127):
        rows = glyphs.get(code) or ['0' * (bytes_per_row * 2)] * h
        for r in range(h):
            hexrow = rows[r] if r < len(rows) else '0' * (bytes_per_row * 2)
            v = int(hexrow, 16) if hexrow else 0
            for b in range(bytes_per_row):
                shift = (bytes_per_row - 1 - b) * 8
                data.append((v >> shift) & 0xFF)
    out.write(f"\n/* {os.path.basename(path)} - Spleen {w}x{h}, "
              f"ASCII 32..126, {len(data)} bytes */\n")
    out.write(f"static const uint8_t {name}_data[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        out.write("  " + ",".join(f"0x{b:02X}" for b in data[i:i+16]) + ",\n")
    out.write("};\n")
    out.write(f"const LB_Font {name} = {{ {w}, {h}, {bytes_per_row}, 32, 126, {name}_data }};\n")
    return name, w, h, len(data)

if len(sys.argv) < 2:
    sys.exit(__doc__.strip())

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "LB_Fonts.cpp")
made = []
with open(OUT, "w") as f:
    f.write("""/*
 * LB_Fonts.cpp - GENERATED by tools/gen_fonts.py. Do not edit by hand.
 *
 * Fonts are Spleen by Frederic Cambus, BSD 2-Clause:
 *
 *   Copyright (c) 2018-2026, Frederic Cambus
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the above copyright notice and
 *   this list of conditions are retained. See THIRD_PARTY.md.
 *
 * A font nobody calls setFont() with costs zero flash - the linker drops it -
 * so this catalogue can grow without every sketch paying for it.
 */
#include "LB_Font.h"
""")
    for p in sys.argv[1:]:
        made.append(emit(p, f))
for n, w, h, sz in made:
    print(f"  {n:16s} {w}x{h}  {sz} bytes")
print(f"wrote {os.path.normpath(OUT)}")
